# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-10 11:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_col_sel', '0004_auto_20171010_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collegedetail',
            name='applied_students',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='college_applied', to='app_col_sel.Student'),
        ),
        migrations.AlterField(
            model_name='collegedetail',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='collegedetail',
            name='course',
            field=models.CharField(max_length=200),
        ),
    ]
